'use server';
import { redirect } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import { z } from 'zod';
import { db } from '@/db/client';
import { requireOwner } from '@/lib/auth';
import { confirmInquiry,changeEvent } from '@/services/events';
import { refreshBusy } from '@/integrations/google/calendar';
import { runJobs } from '@/jobs/runner';
import { currentMonth } from '@/domain/calendar';
const value=(f:FormData,k:string)=>String(f.get(k)||'');
function target(path:string,msg:string,error=false){revalidatePath('/admin/speaking','layout');revalidatePath('/speaking','layout');redirect(path+'?'+(error?'error':'message')+'='+encodeURIComponent(msg));}
function publicError(e:unknown){if(e instanceof z.ZodError)return '請檢查必填欄位與數值。';const m=(e as Error).message;return /[\u3400-\u9fff]/.test(m)?m:'操作未完成，請重新載入或檢查連線。';}
export async function updateInquiry(f:FormData){const user=await requireOwner();const id=z.uuid().parse(value(f,'id'));let error='';try{const status=z.enum(['inquiry','contacted','negotiating','awaiting_confirmation','declined','cancelled']).parse(value(f,'status'));await db.$transaction(async tx=>{const r=await tx.inquiry.updateMany({where:{id,rowVersion:Number(f.get('rowVersion')),status:{not:'converted'}},data:{status,rowVersion:{increment:1}}});if(!r.count)throw new Error('資料已更新或已轉成演講，請重新載入');await tx.activityLog.create({data:{actor:user.id,action:'inquiry.'+status,entityId:id}});});}catch(e){error=publicError(e);}target('/admin/speaking/inquiries/'+id,error||'進度已儲存',!!error);}
export async function confirmAction(f:FormData){const user=await requireOwner();const id=z.uuid().parse(value(f,'id'));let error='',eventId='';try{if(f.get('confirm')!=='on')throw new Error('請先勾選確認建立演講');const i=await db.inquiry.findUniqueOrThrow({where:{id}});if(f.get('manualAvailability')!=='on'){try{await refreshBusy(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit'}).format(i.startsAt));}catch{throw new Error('Google 空檔尚未確認；請先連線或勾選已人工確認時段');}}const fee=value(f,'fee')?z.coerce.number().min(0).max(9999999999).parse(f.get('fee')):undefined;const event=await confirmInquiry({inquiryId:id,rowVersion:z.coerce.number().int().positive().parse(f.get('rowVersion')),topicVersionId:z.uuid().parse(value(f,'topicVersionId')),fee,actor:user.id});eventId=event.id;if(f.get('manualAvailability')==='on')await db.activityLog.create({data:{actor:user.id,action:'calendar.manual_override',entityId:event.id}});}catch(e){error=publicError(e);}if(error)target('/admin/speaking/inquiries/'+id,error,true);target('/admin/speaking/events/'+eventId,'演講已確認，Google 行程等待同步');}
export async function eventAction(f:FormData){const user=await requireOwner();const id=z.uuid().parse(value(f,'id'));let error='';try{if(f.get('confirm')!=='on')throw new Error('請先勾選確認操作');const action=z.enum(['reschedule','prepare','complete','cancel']).parse(value(f,'action'));let startsAt:Date|undefined;if(action==='reschedule'){startsAt=new Date(`${value(f,'date')}T${value(f,'time')}:00+08:00`);if(!Number.isFinite(startsAt.getTime())||startsAt.getTime()<Date.now())throw new Error('請選擇有效的未來日期');if(f.get('manualAvailability')!=='on')throw new Error('請先核對私人行程並勾選人工確認');}await changeEvent({id,rowVersion:Number(f.get('rowVersion')),action,startsAt,actor:user.id});}catch(e){error=publicError(e);}target('/admin/speaking/events/'+id,error||'案件已更新，行程同步已排入佇列',!!error);}
export async function checklistAction(f:FormData){await requireOwner();const eventId=z.uuid().parse(value(f,'eventId'));const event=await db.speakingEvent.findUniqueOrThrow({where:{id:eventId}});if(!['completed','cancelled'].includes(event.status))await db.checklistItem.updateMany({where:{id:z.uuid().parse(value(f,'id')),eventId},data:{completed:value(f,'completed')==='true'}});revalidatePath('/admin/speaking','layout');}
export async function feeAction(f:FormData){const user=await requireOwner();const id=z.uuid().parse(value(f,'id'));let error='';try{const fee=z.coerce.number().min(0).max(9999999999).parse(f.get('fee'));await db.$transaction(async tx=>{const changed=await tx.speakingEvent.updateMany({where:{id,rowVersion:Number(f.get('rowVersion')),status:{in:['confirmed','preparing']}},data:{fee,rowVersion:{increment:1}}});if(!changed.count)throw new Error('資料已更新，請重新載入');await tx.activityLog.create({data:{actor:user.id,action:'fee.updated',entityId:id}});});}catch(e){error=publicError(e);}target('/admin/speaking/events/'+id,error||'費用已更新',!!error);}
export async function createVersion(f:FormData){const user=await requireOwner();let error='';const topicId=value(f,'topicId');try{const label=z.string().trim().min(1).max(100).parse(f.get('label')),audience=z.string().trim().min(1).max(200).parse(f.get('audience')),durationMinutes=z.coerce.number().int().min(30).max(720).parse(f.get('durationMinutes')),outline=z.string().trim().min(10).max(15000).parse(f.get('outline'));await db.$transaction(async tx=>{await tx.counter.update({where:{id:'speaker-lock'},data:{value:{increment:1}}});const last=await tx.topicVersion.findFirst({where:{topicId},orderBy:{version:'desc'}});const v=await tx.topicVersion.create({data:{topicId,label,audience,durationMinutes,outline,version:(last?.version||0)+1}});await tx.activityLog.create({data:{actor:user.id,action:'topic.version_created',entityId:v.id}});});}catch(e){error=publicError(e);}target('/admin/speaking/topics/'+encodeURIComponent(topicId),error||'新版本已保存，既有演講不受影響',!!error);}
export async function saveTopic(f:FormData){const user=await requireOwner();const id=value(f,'id');let error='';try{const title=z.string().trim().min(5).max(300).parse(f.get('title')),summary=z.string().trim().min(10).max(3000).parse(f.get('summary'));await db.$transaction(async tx=>{await tx.topic.update({where:{id},data:{title,summary,published:f.get('published')==='on'}});await tx.activityLog.create({data:{actor:user.id,action:'topic.saved',entityId:id}});});}catch(e){error=publicError(e);}target('/admin/speaking/topics/'+encodeURIComponent(id),error||'主題已儲存',!!error);}
export async function addBlock(f:FormData){const user=await requireOwner();let error='';try{const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(f.get('date')),start=new Date(date+'T00:00:00+08:00');if(!Number.isFinite(start.getTime()))throw new Error('日期不正確');await db.$transaction(async tx=>{await tx.counter.update({where:{id:'speaker-lock'},data:{value:{increment:1}}});const key='manual:'+date;await tx.calendarBlock.upsert({where:{sourceKey:key},create:{sourceKey:key,source:'manual',kind:'unavailable',startsAt:start,endsAt:new Date(start.getTime()+86400000)},update:{active:true}});await tx.activityLog.create({data:{actor:user.id,action:'calendar.blocked',entityId:key}});});}catch(e){error=publicError(e);}target('/admin/speaking/calendar',error||'已標記不接受邀約',!!error);}
export async function releaseBlock(f:FormData){const user=await requireOwner();const id=z.uuid().parse(value(f,'id'));await db.$transaction(async tx=>{await tx.calendarBlock.updateMany({where:{id,source:'manual'},data:{active:false}});await tx.activityLog.create({data:{actor:user.id,action:'calendar.unblocked',entityId:id}});});target('/admin/speaking/calendar','日期已解除人工封鎖');}
export async function syncNow(){await requireOwner();let error='';try{await db.outboxJob.updateMany({where:{status:'needs_attention'},data:{status:'pending',nextAttemptAt:new Date()}});const result=await runJobs();if(result.failed)error='部分行程尚未同步，請检查 Google 連線與日曆設定。';}catch{error='同步未完成，請檢查 Google 設定';}target('/admin/speaking/settings',error||'同步工作已完成',!!error);}
export async function refreshCalendar(f:FormData){await requireOwner();let error='';try{await refreshBusy(value(f,'month')||currentMonth());}catch{error='空檔更新未完成，請檢查 Google 授權與私人日曆 ID。';}target('/admin/speaking/calendar',error||'Google 空檔已更新',!!error);}
export async function saveCalendarSettings(f:FormData){await requireOwner();let error='';try{const calendarId=z.string().trim().min(1).max(300).parse(f.get('calendarId'));const busyCalendarIds=value(f,'busyIds').split('\n').map(x=>x.trim()).filter(Boolean);if(!busyCalendarIds.length||busyCalendarIds.length>20)throw new Error('請填寫 1–20 個私人日曆 ID');if(busyCalendarIds.includes(calendarId))throw new Error('私人日曆請不要包含專用演講日曆，避免與系統行程重複計算');await db.googleConnection.update({where:{id:'owner'},data:{calendarId,busyCalendarIds}});await db.syncState.updateMany({data:{error:'日曆設定已改變，請重新同步'}});}catch(e){error=publicError(e);}target('/admin/speaking/settings',error||'日曆設定已保存，請更新空檔',!!error);}