'use server';
import { z } from 'zod';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { db } from '@/db/client';
import { requireOwner } from '@/lib/auth';
import { createPortal, portalLink, receiptDrafts, sendDraft } from '@/services/studio-workflow';
const str=(f:FormData,k:string)=>String(f.get(k)||'');
const id=(f:FormData,k='id')=>z.uuid().parse(str(f,k));
function done(path:string,message:string){revalidatePath('/admin/speaking','layout');redirect(path+'?message='+encodeURIComponent(message));}
export async function saveQuote(f:FormData){
  const user=await requireOwner(),inquiryId=id(f,'inquiryId');
  const money=(k:string)=>z.coerce.number().finite().min(0).max(99999999).multipleOf(0.01).parse(f.get(k));
  const validUntil=new Date(str(f,'validUntil')+'T23:59:59+08:00');
  if(!Number.isFinite(validUntil.getTime())||validUntil.getTime()<Date.now())throw new Error('請填寫有效期限');
  const data={speakerFee:money('speakerFee'),travelFee:money('travelFee'),otherFee:money('otherFee'),terms:z.string().trim().min(1).max(8000).parse(f.get('terms')),recording:z.string().trim().min(1).max(2000).parse(f.get('recording')),validUntil};
  await db.$transaction(async tx=>{await tx.counter.update({where:{id:'speaker-lock'},data:{value:{increment:1}}});const last=await tx.quote.findFirst({where:{inquiryId},orderBy:{version:'desc'}});await tx.quote.create({data:{inquiryId,version:(last?.version||0)+1,...data}});await tx.activityLog.create({data:{actor:user.id,action:'quote.drafted',entityId:inquiryId}});});
  done('/admin/speaking/inquiries/'+inquiryId+'/cooperation','報價草稿已建立，預覽後可發布給主辦單位');
}
export async function issueQuote(f:FormData){const u=await requireOwner();if(f.get('confirm')!=='on')throw new Error('請確認發布');const q=await db.quote.findUniqueOrThrow({where:{id:id(f)}});if(q.validUntil<new Date())throw new Error('報價已過期');await db.$transaction(async tx=>{await tx.counter.update({where:{id:'speaker-lock'},data:{value:{increment:1}}});const current=await tx.quote.findUniqueOrThrow({where:{id:q.id}});if(current.status!=='draft'||current.validUntil<new Date())throw new Error('此報價已發布或過期');await tx.quote.updateMany({where:{inquiryId:q.inquiryId,status:'issued'},data:{status:'superseded'}});await tx.quote.updateMany({where:{id:q.id,status:'draft'},data:{status:'issued'}});await tx.activityLog.create({data:{actor:u.id,action:'quote.issued',entityId:q.id}});});done('/admin/speaking/inquiries/'+q.inquiryId+'/cooperation','報價已發布至主辦單位頁面');}
export async function portalAction(f:FormData){await requireOwner();const inquiryId=id(f,'inquiryId');if(str(f,'action')==='revoke')await db.organizerPortal.updateMany({where:{inquiryId},data:{revoked:true}});else await createPortal(inquiryId);done('/admin/speaking/inquiries/'+inquiryId+'/cooperation','專屬連結已更新；重新產生時舊連結立即失效');}
export async function materialAction(f:FormData){await requireOwner();const inquiryId=id(f,'inquiryId');const lines=str(f,'materials').split('\n').filter(x=>x.trim());const materials=lines.map(line=>{const [label,...rest]=line.split('|');const url=z.url().parse(rest.join('|').trim());if(new URL(url).protocol!=='https:')throw new Error('素材請使用 HTTPS 網址');return {label:z.string().trim().min(1).max(100).parse(label),url};});if(materials.length>15)throw new Error('最多 15 個素材');await db.organizerPortal.update({where:{inquiryId},data:{materials}});done('/admin/speaking/inquiries/'+inquiryId+'/cooperation','主辦方素材已儲存');}
export async function draftPortalMail(f:FormData){await requireOwner();const inquiryId=id(f,'inquiryId');const p=await db.organizerPortal.findUniqueOrThrow({where:{inquiryId},include:{inquiry:true}});if(p.revoked||p.expiresAt<new Date())throw new Error('請先更新專屬連結');await db.mailDraft.create({data:{inquiryId,dedupeKey:'portal:'+crypto.randomUUID(),recipient:p.inquiry.email,subject:`演講合作確認與資料｜${p.inquiry.organization}`,body:`${p.inquiry.contactName} 您好：\n\n請使用以下專屬連結查看報價、確認需求及取得講師素材：\n${portalLink(p)}\n\n連結含有貴單位資料，請勿公開轉傳。有效期限：${p.expiresAt.toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei'})}。\n\n強尼老師｜劉宗騰`}});done('/admin/speaking/mail','專屬頁通知已存為草稿，請預覽後寄出');}
export async function backfillMail(){await requireOwner();const rows=await db.inquiry.findMany({orderBy:{createdAt:'desc'},take:100});await db.$transaction(async tx=>{for(const i of rows)await receiptDrafts(tx,i);},{timeout:30000});done('/admin/speaking/mail','最近 100 筆邀約的收件草稿已補齊，未寄出');}
export async function sendMail(f:FormData){const u=await requireOwner();if(f.get('confirm')!=='on')throw new Error('請先確認收件人與內容');let message='信件已交由 Gmail 寄出';try{await sendDraft(id(f));await db.activityLog.create({data:{actor:u.id,action:'mail.sent',entityId:id(f)}});}catch(e){message=(e as Error).message;}done('/admin/speaking/mail',message);}
export async function editMail(f:FormData){await requireOwner();await db.mailDraft.updateMany({where:{id:id(f),status:'draft'},data:{subject:z.string().trim().min(1).max(200).parse(f.get('subject')),body:z.string().trim().min(1).max(15000).parse(f.get('body'))}});done('/admin/speaking/mail','草稿已保存');}
export async function taskAction(f:FormData){await requireOwner();const eventId=id(f,'eventId');if(f.get('taskId'))await db.preparationTask.updateMany({where:{id:id(f,'taskId'),eventId},data:{completed:f.get('completed')==='true'}});else{const dueAt=new Date(str(f,'dueAt')+'T09:00:00+08:00');if(!Number.isFinite(dueAt.getTime()))throw new Error('請填寫日期');await db.preparationTask.create({data:{eventId,label:z.string().trim().min(1).max(300).parse(f.get('label')),dueAt}});}done('/admin/speaking/preparation','準備事項已更新');}
export async function reviewFeedback(f:FormData){const u=await requireOwner();const feedback=await db.feedback.findUniqueOrThrow({where:{id:id(f)}});const publish=f.get('publish')==='true';if(publish&&!feedback.publishConsent)throw new Error('主辦單位尚未同意公開');await db.$transaction(async tx=>{await tx.feedback.update({where:{id:feedback.id},data:{published:publish}});await tx.activityLog.create({data:{actor:u.id,action:publish?'feedback.published':'feedback.hidden',entityId:feedback.id}});});revalidatePath('/speaking/stories');done('/admin/speaking/feedback','回饋公開狀態已更新');}
