"use client";
import { websiteFetch } from "./request";

import { useEffect, useState } from "react";
import { ImageIcon, Loader2, Save } from "lucide-react";
import { Button } from "./ui";
import { Input } from "./ui";
import { Textarea } from "./ui";

type MediaRow = { id: number; originalFilename: string; title: string; category: string; date: string | null; location: string | null; relatedProject: string | null; relatedArticle: string | null; relatedAchievement: string | null; relatedSpeakingRecord: string | null; photographerSource: string | null; permissionStatus: string; altText: string; caption: string | null; primaryTopic: string | null; secondaryTopics: string | null; allowedPlacements: string | null; doNotUseFor: string | null; featured: number; visibility: string; imageUrl: string | null };
const categoryLabel: Record<string, string> = { brand: "A｜人物形象", teaching: "B｜教學現場", achievement: "C｜成果／競賽", collaboration: "D｜教師社群／合作" };

export function MediaLibraryManager() {
  const [items, setItems] = useState<MediaRow[]>([]); const [selected, setSelected] = useState<MediaRow | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  async function load() { setLoading(true); const response = await websiteFetch("/api/admin/website/media-library", { cache: "no-store" }); const rows = response.ok ? await response.json() as MediaRow[] : []; setItems(rows); setSelected((current) => current ? rows.find((row) => row.id === current.id) || rows[0] || null : rows[0] || null); setLoading(false); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  function update<K extends keyof MediaRow>(key: K, value: MediaRow[K]) { if (selected) setSelected({ ...selected, [key]: value }); }
  async function save() { if (!selected) return; setMessage("儲存中……"); const response = await websiteFetch("/api/admin/website/media-library", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(selected) }); setMessage(response.ok ? "照片 Metadata 已更新。" : "儲存失敗"); if (response.ok) await load(); }
  const field = (key: keyof MediaRow, label: string) => <label>{label}<Input value={String(selected?.[key] || "")} onChange={(event) => update(key, event.target.value as never)} /></label>;
  return <section className="media-library-manager"><div className="content-manager-heading"><div><p className="overline">MEDIA LIBRARY METADATA</p><h2>真實照片與公開權限</h2><p>目前已辨識 15 張新素材。清楚未成年正面照預設為 internal only；授權未知素材不會進入首頁大型位置。</p></div><span className="media-count"><ImageIcon /> {items.length} 張</span></div>
    <div className="content-manager-grid"><aside>{loading ? <p><Loader2 className="studio-spin" /> 讀取中</p> : items.map((item) => <button key={item.id} className={selected?.id === item.id ? "active" : ""} onClick={() => setSelected(item)}><span>{categoryLabel[item.category]}・{item.permissionStatus}</span><strong>{item.title}</strong><small>{item.originalFilename}</small></button>)}</aside>
      {selected && <div className="profile-entry-form"><div className="studio-two">{field("title", "Title")}{field("originalFilename", "Original filename")}</div><div className="studio-two"><label>Category<select value={selected.category} onChange={(event) => update("category", event.target.value)}>{Object.entries(categoryLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Permission status<select value={selected.permissionStatus} onChange={(event) => update("permissionStatus", event.target.value)}><option value="approved_public">approved_public</option><option value="limited_use">limited_use</option><option value="internal_only">internal_only</option><option value="unknown">unknown</option></select></label></div><div className="studio-two">{field("date", "Date")}{field("location", "Location")}</div><div className="studio-two">{field("primaryTopic", "Primary topic")}{field("secondaryTopics", "Secondary topics（逗號分隔）")}</div><div className="studio-two">{field("relatedProject", "Related project")}{field("relatedArticle", "Related article")}</div><div className="studio-two">{field("allowedPlacements", "Allowed placements")}{field("doNotUseFor", "Do not use for")}</div><div className="studio-two">{field("relatedAchievement", "Related achievement")}{field("relatedSpeakingRecord", "Related speaking record")}</div><div className="studio-two">{field("photographerSource", "Photographer / source")}{field("imageUrl", "Image URL")}</div><label>Alt text<Textarea value={selected.altText} onChange={(event) => update("altText", event.target.value)} /></label><label>Caption<Textarea value={selected.caption || ""} onChange={(event) => update("caption", event.target.value)} /></label><div className="studio-two"><label>Featured<select value={String(selected.featured)} onChange={(event) => update("featured", Number(event.target.value))}><option value="0">No</option><option value="1">Yes</option></select></label><label>Public / private<select value={selected.visibility} onChange={(event) => update("visibility", event.target.value)}><option value="private">private</option><option value="public">public</option></select></label></div>{message && <p className="studio-message">{message}</p>}<div className="content-actions"><Button onClick={() => void save()}><Save /> 儲存照片資料</Button></div></div>}
    </div></section>;
}
