"use client";
import { websiteFetch } from "./request";

import { useCallback, useEffect, useState } from "react";
import { FileUp, ImagePlus, Loader2, Plus, Save, Trash2 } from "lucide-react";
import { Tabs, TabsList, TabsTrigger } from "./ui";
import { Button } from "./ui";
import { Input } from "./ui";
import { Textarea } from "./ui";

type Entry = { id: number; category: string; year: string | null; name: string; type: string | null; role: string | null; organization: string | null; result: string | null; description: string | null; image: string | null; proofDocument: string | null; externalUrl: string | null; certificateUrl: string | null; officialAnnouncementUrl: string | null; activityPhotoUrl: string | null; submissionProofUrl: string | null; coverImageUrl: string | null; officialUrl: string | null; videoUrl: string | null; pdfUrl: string | null; researchDocumentUrl: string | null; posterUrl: string | null; visibility: "private" | "public"; evidenceStatus: "evidence_pending" | "in_progress" | "verified" };
type Draft = Omit<Entry, "id"> & { id?: number };
const categories = [
  ["education", "Education｜學歷／師培"], ["research", "Research｜研究"], ["publications", "Publications｜研究與發表"], ["personal_awards", "Personal Awards｜個人獎項"], ["student_guidance", "Student Guidance｜學生指導"], ["student_awards", "Student Awards｜指導成果"], ["long_term_programs", "Long-term Programs｜長期實踐"], ["professional_development", "Professional Development｜專業進修"], ["certifications", "Certifications｜資格／證書"],
] as const;
const blank = (category: string): Draft => ({ category, year: null, name: "", type: null, role: null, organization: null, result: null, description: null, image: null, proofDocument: null, externalUrl: null, certificateUrl: null, officialAnnouncementUrl: null, activityPhotoUrl: null, submissionProofUrl: null, coverImageUrl: null, officialUrl: null, videoUrl: null, pdfUrl: null, researchDocumentUrl: null, posterUrl: null, visibility: "private", evidenceStatus: "evidence_pending" });

export function ProfileEntriesManager() {
  const [category, setCategory] = useState("education"); const [items, setItems] = useState<Entry[]>([]); const [draft, setDraft] = useState<Draft>(blank("education"));
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async (selected: string) => { setLoading(true); const response = await websiteFetch(`/api/admin/website/profile-entries?category=${selected}`, { cache: "no-store" }); setItems(response.ok ? await response.json() : []); setLoading(false); }, []);
  useEffect(() => { void load(category); }, [category, load]);
  function changeCategory(value: string) { setCategory(value); setDraft(blank(value)); setMessage(""); }
  async function upload(file: File, field: keyof Draft) { const form = new FormData(); form.append("file", file); setMessage("證據檔案上傳中……"); const response = await websiteFetch("/api/admin/website/upload", { method: "POST", body: form }); const result = await response.json() as { url?: string; error?: string }; if (response.ok && result.url) { setDraft((current) => ({ ...current, [field]: result.url! })); setMessage("已上傳；請儲存此筆成果。"); } else setMessage(result.error || "上傳失敗"); }
  async function save(visibility: "private" | "public") { setSaving(true); const response = await websiteFetch(draft.id ? `/api/admin/website/profile-entries/${draft.id}` : "/api/admin/website/profile-entries", { method: draft.id ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...draft, category, visibility }) }); const result = await response.json() as Entry & { error?: string }; setSaving(false); if (!response.ok) { setMessage(result.error || "儲存失敗"); return; } setDraft(result); setMessage(visibility === "public" ? "已標記為公開資料。" : "已儲存為後台資料。"); await load(category); }
  async function remove() { if (!draft.id || !window.confirm(`確定刪除「${draft.name}」？`)) return; const response = await websiteFetch(`/api/admin/website/profile-entries/${draft.id}`, { method: "DELETE" }); if (!response.ok) { const result = await response.json() as { error?: string }; setMessage(result.error || "刪除未完成，原資料仍保留。"); return; } setDraft(blank(category)); setMessage("資料已刪除。"); await load(category); }
  const textField = (key: keyof Draft, label: string, placeholder = "") => <label>{label}<Input value={String(draft[key] || "")} onChange={(event) => setDraft({ ...draft, [key]: event.target.value })} placeholder={placeholder} /></label>;
  const uploadField = (key: keyof Draft, label: string, accept: string, icon: "image" | "file" = "file") => <div><label>{label}<Input value={String(draft[key] || "")} onChange={(event) => setDraft({ ...draft, [key]: event.target.value })} placeholder="上傳後自動填入，或貼上網址" /></label><label className="studio-upload-button"><input type="file" accept={accept} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file, key); event.target.value = ""; }} />{icon === "image" ? <ImagePlus /> : <FileUp />} 上傳</label></div>;
  return <section className="profile-entries-manager"><div className="content-manager-heading"><div><p className="overline">PROFILE RECORDS CMS</p><h2>成果與專業歷程資料庫</h2><p>管理學歷、研究、發表、獎項、學生指導、長期計畫、進修與證書。沒有證據檔案時會保留 Evidence pending。</p></div><Button onClick={() => setDraft(blank(category))}><Plus /> 新增資料</Button></div>
    <Tabs value={category} onValueChange={changeCategory}><TabsList className="content-tabs">{categories.map(([value, label]) => <TabsTrigger value={value} key={value}>{label}</TabsTrigger>)}</TabsList></Tabs>
    <div className="content-manager-grid"><aside>{loading ? <p><Loader2 className="studio-spin" /> 讀取中</p> : items.length === 0 ? <p>此分類尚未建立後台紀錄。</p> : items.map((item) => <button className={draft.id === item.id ? "active" : ""} key={item.id} onClick={() => setDraft(item)}><span>{item.visibility === "public" ? "公開" : "未公開"}・{item.evidenceStatus === "verified" ? "Evidence verified" : item.evidenceStatus === "in_progress" ? "進行中" : "Evidence pending"}</span><strong>{item.name}</strong><small>{item.year || item.result || item.organization}</small></button>)}</aside>
      <div className="profile-entry-form"><div className="studio-two">{textField("year", "年份", "例如：2026")}{textField("name", "名稱")}</div><div className="studio-two">{textField("type", "類別／型態")}{textField("role", "角色")}</div><div className="studio-two">{textField("organization", "單位")}{textField("result", "成果／狀態")}</div><label>說明<Textarea value={draft.description || ""} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><div className="studio-two">{textField("externalUrl", "External URL", "https://...")}{textField("officialUrl", "官方網址", "https://...")}</div><div className="studio-two">{textField("officialAnnouncementUrl", "官方公告", "https://...")}<label>證據狀態<select value={draft.evidenceStatus === ("pending" as Draft["evidenceStatus"]) ? "evidence_pending" : draft.evidenceStatus} onChange={(event) => setDraft({ ...draft, evidenceStatus: event.target.value as Draft["evidenceStatus"] })}><option value="evidence_pending">Evidence pending</option><option value="verified">已附公開成果資料</option><option value="in_progress">進行中</option></select></label></div><div className="studio-two">{textField("videoUrl", "成果影片網址", "https://...")}{textField("pdfUrl", "PDF 網址", "https://...")}</div><div className="studio-two">{textField("researchDocumentUrl", "研究文件網址", "https://...")}{textField("posterUrl", "海報網址", "https://...")}</div><div className="evidence-upload-grid">{uploadField("image", "圖片", "image/jpeg,image/png,image/webp", "image")}{uploadField("certificateUrl", "獎狀／證書", "image/jpeg,image/png,image/webp,application/pdf")}{uploadField("proofDocument", "證明文件", "image/jpeg,image/png,image/webp,application/pdf")}{uploadField("activityPhotoUrl", "活動照片", "image/jpeg,image/png,image/webp", "image")}{uploadField("submissionProofUrl", "投稿證明", "image/jpeg,image/png,image/webp,application/pdf")}{uploadField("coverImageUrl", "作品封面／成果海報", "image/jpeg,image/png,image/webp,application/pdf", "image")}</div>{message && <p className="studio-message">{message}</p>}<div className="content-actions">{draft.id && <Button variant="destructive" onClick={() => void remove()}><Trash2 /> 刪除</Button>}<Button variant="outline" disabled={saving} onClick={() => void save("private")}><Save /> 儲存未公開</Button><Button disabled={saving} onClick={() => void save("public")}>{saving && <Loader2 className="studio-spin" />} 標記公開</Button></div></div>
    </div></section>;
}
