import { createCipheriv,createDecipheriv,createHash,randomBytes } from 'node:crypto';
import { db } from '@/db/client';
import { monthRange } from '@/domain/calendar';
export function seal(text:string){if(!process.env.NEXTAUTH_SECRET)throw new Error('CONFIG_REQUIRED');const key=createHash('sha256').update(process.env.NEXTAUTH_SECRET).digest(),iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv);const data=Buffer.concat([cipher.update(text,'utf8'),cipher.final()]);return [iv,cipher.getAuthTag(),data].map(x=>x.toString('base64url')).join('.');}
export function unseal(text:string){if(!process.env.NEXTAUTH_SECRET)throw new Error('CONFIG_REQUIRED');const [iv,tag,data]=text.split('.').map(x=>Buffer.from(x,'base64url'));const cipher=createDecipheriv('aes-256-gcm',createHash('sha256').update(process.env.NEXTAUTH_SECRET).digest(),iv);cipher.setAuthTag(tag);return Buffer.concat([cipher.update(data),cipher.final()]).toString('utf8');}
export async function googleConfig(){const c=await db.googleConnection.findUnique({where:{id:'owner'}});return {refresh:c?unseal(c.refreshTokenEncrypted):process.env.GOOGLE_REFRESH_TOKEN||'',calendarId:c?.calendarId||process.env.GOOGLE_CALENDAR_ID||'',busyIds:c?.busyCalendarIds||process.env.GOOGLE_BUSY_CALENDAR_IDS?.split(',').filter(Boolean)||[]};}
export async function accessToken(){const c=await googleConfig();if(!c.refresh||!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)throw new Error('GOOGLE_NOT_CONNECTED');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:c.refresh,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('GOOGLE_AUTH_REQUIRED');return (await r.json()).access_token as string;}
export async function refreshBusy(month:string){
  try{const c=await googleConfig();if(!c.busyIds.length)throw new Error('GOOGLE_CALENDARS_REQUIRED');const token=await accessToken(),{start,end}=monthRange(month);const r=await fetch('https://www.googleapis.com/calendar/v3/freeBusy',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({timeMin:start.toISOString(),timeMax:end.toISOString(),timeZone:'Asia/Taipei',items:c.busyIds.map(id=>({id}))}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('GOOGLE_BUSY_FAILED');const result=await r.json();const blocks:{startsAt:Date;endsAt:Date}[]=[];
    for(const id of c.busyIds){const calendar=result.calendars?.[id];if(!calendar||calendar.errors?.length||!Array.isArray(calendar.busy))throw new Error('GOOGLE_BUSY_INCOMPLETE');for(const b of calendar.busy){const startsAt=new Date(b.start),endsAt=new Date(b.end);if(!Number.isFinite(startsAt.getTime())||!Number.isFinite(endsAt.getTime())||endsAt<=startsAt)throw new Error('GOOGLE_BUSY_INVALID');blocks.push({startsAt,endsAt});}}
    await db.$transaction(async tx=>{await tx.counter.update({where:{id:'speaker-lock'},data:{value:{increment:1}}});await tx.calendarBlock.deleteMany({where:{source:'google_freebusy',sourceKey:{startsWith:'busy:'+month+':'}}});if(blocks.length)await tx.calendarBlock.createMany({data:blocks.map((b,i)=>({...b,source:'google_freebusy',sourceKey:`busy:${month}:${i}`,kind:'busy'}))});await tx.syncState.upsert({where:{id:'freebusy:'+month},create:{id:'freebusy:'+month,lastSuccessAt:new Date()},update:{lastSuccessAt:new Date(),error:null}});});
  }catch(e){await db.syncState.upsert({where:{id:'freebusy:'+month},create:{id:'freebusy:'+month,error:'同步尚未成功'},update:{error:'同步尚未成功'}});throw e;}
}
export function externalEventId(id:string){return 'spk'+id.replaceAll('-','').toLowerCase();}
export async function syncEvent(eventId:string){const event=await db.speakingEvent.findUniqueOrThrow({where:{id:eventId}}),c=await googleConfig();if(!c.calendarId)throw new Error('GOOGLE_CALENDAR_REQUIRED');const token=await accessToken(),id=externalEventId(event.id),root=`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(c.calendarId)}/events`,headers={Authorization:'Bearer '+token,'Content-Type':'application/json'};
  if(event.status==='cancelled'){const r=await fetch(root+'/'+id+'?sendUpdates=none',{method:'DELETE',headers,signal:AbortSignal.timeout(15000)});if(!r.ok&&![404,410].includes(r.status))throw new Error('GOOGLE_SYNC_'+r.status);return;}
  const body={summary:event.title,description:event.code,start:{dateTime:event.startsAt.toISOString(),timeZone:event.timezone},end:{dateTime:event.endsAt.toISOString(),timeZone:event.timezone},extendedProperties:{private:{speakingEventId:event.id,version:String(event.rowVersion)}}};
  let r=await fetch(root+'/'+id+'?sendUpdates=none',{method:'PATCH',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});
  if(r.status===404){r=await fetch(root+'?sendUpdates=none',{method:'POST',headers,body:JSON.stringify({...body,id}),signal:AbortSignal.timeout(15000)});if(r.status===409)r=await fetch(root+'/'+id+'?sendUpdates=none',{method:'PATCH',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});}
  if(!r.ok)throw new Error('GOOGLE_SYNC_'+r.status);
}