'use client';
import { useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight,ArrowLeft } from 'lucide-react';
import { audienceOptions } from '@/domain/inquiry';
type Option={id:string;title:string};
export function InviteForm({topics,selectedTopic,sourceUrl}:{topics:Option[];selectedTopic?:string;sourceUrl?:string}){
  const router=useRouter(),form=useRef<HTMLFormElement>(null),key=useRef('');
  const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
  function advance(){const current=form.current?.querySelector<HTMLElement>(`[data-step="${step}"]`);const inputs=current?.querySelectorAll<HTMLInputElement>('input,select,textarea');for(const input of inputs||[]){if(!input.reportValidity())return;}setError('');setStep(step+1);}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(step<3){advance();return;}if(busy)return;const f=new FormData(e.currentTarget);if(!key.current)key.current=crypto.randomUUID();const data:Record<string,unknown>=Object.fromEntries(f.entries());data.audiences=f.getAll('audiences');for(const k of ['interaction','workshop','worksheet','customContent','consent'])data[k]=f.get(k)==='on';data.idempotencyKey=key.current;setBusy(true);setError('');try{const r=await fetch('/api/public/v1/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await r.json();if(!r.ok){const fields=body.fields?Object.values(body.fields).flat().join('；'):'';throw new Error(fields||body.error);}router.push('/speaking/invite/thanks');}catch(e){setError((e as Error).message||'暫時無法送出，請稍後再試。');}finally{setBusy(false);}}
  return <form ref={form} onSubmit={submit} className="form-panel" noValidate><div className="form-steps">{['活動與聯絡','分享需求','確認送出'].map((s,i)=><div key={s} className={'form-step '+(step===i+1?'current':'')} aria-current={step===i+1?'step':undefined}><b>{i+1}</b>{s}</div>)}</div><div className="honey" aria-hidden="true"><label>網站<input name="website" tabIndex={-1} autoComplete="off"/></label></div>
    <div data-step="1" hidden={step!==1}><h3>先認識這場活動。</h3><p className="field-hint">除了額外備註，以下欄位皆為必填。</p><div className="field-grid"><Field label="邀約單位" name="organization" placeholder="學校、社群或教育單位"/><Field label="聯絡人" name="contactName" autoComplete="name"/><Field label="聯絡 Email" name="email" type="email" autoComplete="email"/><Field label="聯絡電話" name="phone" type="tel" autoComplete="tel"/><Field label="活動日期" name="date" type="date"/><Field label="開始時間" name="time" type="time" defaultValue="14:00"/><Field label="預計時長（分鐘）" name="durationMinutes" type="number" min="30" max="720" defaultValue="90"/><Field label="預計人數" name="attendees" type="number" min="1" max="10000" defaultValue="30"/><label className="field">活動地區<select name="region" required defaultValue=""><option value="" disabled>選擇地區</option>{['嘉義市','嘉義縣','台南','高雄','台中','台北','新北','桃園','新竹','苗栗','彰化','南投','雲林','屏東','宜蘭','花蓮','台東','澎湖','金門','連江','線上','其他'].map(x=><option key={x}>{x}</option>)}</select></label><Field label="活動地點" name="venue" placeholder="學校／場地／線上平台"/></div><p className="field-hint">時間以台灣時間（Asia/Taipei）為準；提出日期不代表已完成預約。</p></div>
    <div data-step="2" hidden={step!==2}><h3>你們希望帶走什麼？</h3><label className="field">想邀請的主題<select name="topicId" defaultValue={selectedTopic||''}><option value="">尚未決定／提出客製需求</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label className="field">客製主題或想討論的方向（未選講題時必填）<input name="customTopic" maxLength={500} placeholder="也可以告訴我，你們正在面對什麼…"/></label><fieldset style={{border:0,padding:0,margin:'20px 0'}}><legend style={{marginBottom:10,fontSize:14}}>參與對象（可複選，至少一項）</legend><div className="checks">{audienceOptions.map(a=><label className="check" key={a}><input type="checkbox" name="audiences" value={a}/>{a}</label>)}</div></fieldset><Field label="年級／年齡補充（選填）" name="ageRange" required={false} placeholder="例如：國二學生／30–50 歲教師"/><label className="field">希望解決的問題<textarea name="problems" required maxLength={3000} placeholder="目前的困難、課程情境，或希望有所改變的地方。"/></label><label className="field">希望參與者帶走什麼？<textarea name="takeaways" required maxLength={3000} placeholder="一個新觀點、一份課程草案，或能回到現場使用的方法。"/></label><div className="checks" style={{margin:'20px 0'}}>{[['interaction','需要互動'],['workshop','需要工作坊'],['worksheet','需要學習單'],['customContent','需要客製內容']].map(([v,l])=><label className="check" key={v}><input type="checkbox" name={v}/>{l}</label>)}</div><Field label="場地設備" name="equipment" placeholder="例如：投影機、麥克風、Wi-Fi；尚未確定也可註明"/><label className="field">其他需求（選填）<textarea name="notes" maxLength={3000}/></label></div>
    <div data-step="3" hidden={step!==3}><h3>讓這次對話開始。</h3><p>送出後將由講師檢視需求，再與您聯繫討論內容、時間與合作細節。</p><label className="field">如何找到強尼老師？<select name="discovery" defaultValue={sourceUrl?'Blog':'Blog'}>{['Google','Blog','Facebook','Instagram','他人推薦','曾參與演講','其他'].map(x=><option key={x}>{x}</option>)}</select></label><Field label="來源文章網址（選填）" name="sourceUrl" type="url" defaultValue={sourceUrl||''} required={false}/><div className="notice">這是邀約需求，不是即時訂位。講師確認前，日期不會保留，也不會產生費用。</div><label className="check"><input type="checkbox" name="consent" required/>我已閱讀<a className="text-link" href="/privacy" target="_blank" rel="noreferrer">資料使用說明</a>，同意用於邀約聯絡。</label></div>
    {error&&<div className="notice error" role="alert">{error}</div>}<div className="form-actions">{step>1?<button type="button" className="button secondary" onClick={()=>{setError('');setStep(step-1)}}><ArrowLeft size={16}/> 上一步</button>:<span/>}{step<3?<button type="button" className="button" onClick={advance}>下一步 <ArrowRight size={16}/></button>:<button className="button" type="submit" disabled={busy}>{busy?'正在送出…':'送出演講邀約'} <ArrowRight size={16}/></button>}</div></form>;
}
function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="field">{label}<input required maxLength={500} {...props}/></label>}