import Link from 'next/link';
import { notFound } from 'next/navigation';
import { db } from '@/db/client';
import { requireOwner } from '@/lib/auth';
import { portalLink } from '@/services/studio-workflow';
import { QuoteSummary } from '@/components/quote-summary';
import { PrintButton } from '@/components/print-button';
import { AdminFeedback } from '@/components/admin-feedback';
import { saveQuote,issueQuote,portalAction,materialAction,draftPortalMail } from '../../../workflow-actions';
export default async function Cooperation({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{message?:string}>}){
 await requireOwner();const {id}=await params,i=await db.inquiry.findUnique({where:{id},include:{quotes:{orderBy:{version:'desc'}},portal:true}});if(!i)notFound();const p=i.portal;
 return <><Link href={'/admin/speaking/inquiries/'+id}>← 邀約明細</Link><h1>{i.organization} · 合作文件</h1><AdminFeedback {...await searchParams}/><section className="panel no-print"><h2>建立報價新版本</h2><p>請自行確認付款、稅務、取消與錄影條件。儲存草稿後可預覽與列印，再發布給主辦單位。</p><form action={saveQuote}><input name="inquiryId" type="hidden" value={id}/><div className="field-grid">{[['speakerFee','演講費'],['travelFee','交通費'],['otherFee','其他費用']].map(([name,label])=><label className="field" key={name}>{label} TWD<input type="number" min="0" max="99999999" step="0.01" name={name} defaultValue="0" required/></label>)}<label className="field">有效期限<input type="date" name="validUntil" required/></label></div><label className="field">付款、稅務、取消及合作條件<textarea name="terms" required maxLength={8000} placeholder="填入雙方實際約定，包含費用是否含稅、付款時間、改期與取消處理。"/></label><label className="field">錄影與素材使用約定<textarea name="recording" required maxLength={2000} placeholder="填入本次是否允許錄影、用途與使用範圍。"/></label><button className="button">儲存報價草稿</button></form></section>{i.quotes.map(q=><section className="panel" key={q.id}><span className="badge">{{draft:'草稿',issued:'已發布',accepted:'主辦方已確認',superseded:'已被新版取代'}[q.status]||q.status}</span><QuoteSummary quote={q}/><PrintButton/>{q.status==='draft'&&<form action={issueQuote} className="no-print"><input type="hidden" name="id" value={q.id}/><label className="check"><input type="checkbox" name="confirm" required/>確認發布此版本到主辦單位專屬頁</label><button className="button">發布此報價</button></form>}</section>)}<section className="panel no-print"><h2>主辦單位專屬頁</h2>{p&&!p.revoked&&p.expiresAt>new Date()?<><p><a className="text-link" href={portalLink(p)} target="_blank" rel="noreferrer">開啟主辦方專屬頁 ↗</a></p><label className="field">私人連結（可複製給指定窗口）<input readOnly value={portalLink(p)}/></label><p>有效期限：{p.expiresAt.toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei'})}</p><form action={draftPortalMail}><input type="hidden" name="inquiryId" value={id}/><button className="button">建立主辦方通知草稿</button></form></>:<p>尚無有效連結。</p>}<form action={portalAction} style={{marginTop:16}}><input type="hidden" name="inquiryId" value={id}/><button name="action" value="create" className="button secondary">{p?'重新產生連結（舊連結失效）':'建立私人連結'}</button>{p&&!p.revoked&&<button name="action" value="revoke" className="button secondary">撤銷連結</button>}</form>{p&&<><h3 style={{marginTop:24}}>主辦方補充</h3><p style={{whiteSpace:'pre-wrap'}}>{p.organizerNotes||'尚未提供'}</p><p>{p.confirmedAt?'最後確認：'+p.confirmedAt.toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}):'尚未確認需求'}</p><form action={materialAction}><input name="inquiryId" type="hidden" value={id}/><label className="field">提供主辦方的素材（每行：名稱 | HTTPS 網址）<textarea name="materials" defaultValue={Array.isArray(p.materials)?(p.materials as {label:string;url:string}[]).map(m=>m.label+' | '+m.url).join('\n'):''}/></label><button className="button">儲存素材連結</button></form></>}</section></>
}