import { notFound } from 'next/navigation';
import { findPortal } from '@/services/studio-workflow';
import { displayDate,statusLabels } from '@/domain/inquiry';
import { organizerAction } from '../actions';
import { QuoteSummary } from '@/components/quote-summary';
import { PrintButton } from '@/components/print-button';
export const dynamic='force-dynamic';
export const metadata={title:'演講合作專屬頁',robots:{index:false,follow:false},referrer:'no-referrer' as const};
export default async function Organizer({params,searchParams}:{params:Promise<{token:string}>;searchParams:Promise<{saved?:string}>}){
 const {token}=await params,p=await findPortal(token);if(!p)notFound();const i=p.inquiry,e=i.event,q=i.quotes[0];const materials=Array.isArray(p.materials)?p.materials as {label:string;url:string}[]:[];
 return <main className="prose organizer"><p className="eyebrow">強尼老師｜演講合作</p><h1>{i.organization} 專屬頁</h1>{(await searchParams).saved&&<p role="status" className="notice">已保存，講師可在工作室查看。</p>}<section className="panel"><h2>{e?.title||i.topic?.title||i.customTopic}</h2><p>進度：{statusLabels[e?.status||i.status]}<br/>時間：{displayDate(e?.startsAt||i.startsAt)}<br/>地點：{e?.venue||i.venue}<br/>人數：{e?.attendees||i.attendees}</p><p>連結僅供貴單位使用，請勿公開轉傳。</p></section>{q&&<section className="panel"><QuoteSummary quote={q}/><PrintButton/>{q.status==='issued'&&q.validUntil>new Date()&&<form action={organizerAction} className="no-print"><input type="hidden" name="token" value={token}/><input type="hidden" name="action" value="accept"/><input type="hidden" name="quoteId" value={q.id}/><label className="field">確認人姓名<input name="name" maxLength={100} required/></label><label className="check"><input type="checkbox" name="confirm" required/>已閱讀本版費用、條件與錄影約定，同意此合作內容。</label><button className="button">確認合作內容</button></form>}</section>}<section className="panel no-print"><h2>活動需求確認</h2><form action={organizerAction}><input type="hidden" name="token" value={token}/><input type="hidden" name="action" value="confirm"/><label className="field">設備、參與人數、當日窗口與需調整事項<textarea name="notes" maxLength={4000} defaultValue={p.organizerNotes}/></label><button className="button">送出確認與補充</button></form></section><section className="panel"><h2>講師與活動素材</h2><p><a href="https://john-liu-edu.sgi00307.chatgpt.site/speaker-kit" rel="noreferrer">講師介紹與 Speaker Kit →</a></p>{materials.map(m=><p key={m.url}><a href={m.url} rel="noreferrer" target="_blank">{m.label} ↗</a></p>)}</section>{e&&e.endsAt<new Date()&&e.status!=='cancelled'&&<section className="panel no-print"><h2>活動回饋</h2><form action={organizerAction}><input type="hidden" name="token" value={token}/><input type="hidden" name="action" value="feedback"/><label className="field">填寫者／公開署名<input name="name" required maxLength={100} defaultValue={p.feedback?.name}/></label><label className="field">整體評分<select name="rating" defaultValue={p.feedback?.rating||5}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} 分</option>)}</select></label><label className="field">活動心得<textarea name="comment" required maxLength={4000} defaultValue={p.feedback?.comment}/></label><label className="field">最有幫助的收穫<textarea name="takeaway" required maxLength={4000} defaultValue={p.feedback?.takeaway}/></label><label className="field">照片分享網址（選填，請先確認照片使用權限）<input name="photoUrl" type="url" defaultValue={p.feedback?.photoUrl}/></label><label className="check"><input type="checkbox" name="publishConsent" defaultChecked={p.feedback?.publishConsent}/>同意講師審核後公開本次署名、文字心得與成果；照片需另行確認授權。</label><button className="button">保存回饋</button></form></section>}<p><a href="mailto:sgi00307@gmail.com">聯絡講師：sgi00307@gmail.com</a></p></main>
}
